development: &default
  mode:          <%= ENV['PAYPAL_MODE'] %>
  client_id:     <%= ENV['PAYPAL_CLIENT_ID'] %>
  client_secret: <%= ENV['PAYPAL_CLIENT_SECRET'] %>

staging:
  mode:          <%= ENV['PAYPAL_MODE'] %>
  client_id:     <%= ENV['PAYPAL_CLIENT_ID'] %>
  client_secret: <%= ENV['PAYPAL_CLIENT_SECRET'] %>

production:
  mode:          <%= ENV['PAYPAL_MODE'] %>
  client_id:     <%= ENV['PAYPAL_CLIENT_ID'] %>
  client_secret: <%= ENV['PAYPAL_CLIENT_SECRET'] %>
