# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base:        <%= ENV["SECRET_KEY_BASE"] %>
  paypal_host:            <%= ENV["PAYPAL_HOST"] %>
  domain_url:             <%= ENV["DOMAIN_URL"] %>
  api_username:           <%= ENV["API_USERNAME"] %>
  api_password:           <%= ENV["API_PASSWORD"] %>
  aws_access_key_id:      <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key:  <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  paypal_username:        <%= ENV['PAYPAL_USERNAME'] %>
  paypal_password:        <%= ENV['PAYPAL_PASSWORD'] %>
  paypal_signature:       <%= ENV['PAYPAL_SIGNATURE'] %>

staging:
  secret_key_base:        <%= ENV["SECRET_KEY_BASE"] %>
  paypal_host:            <%= ENV["PAYPAL_HOST"] %>
  domain_url:             <%= ENV["DOMAIN_URL"] %>
  api_username:           <%= ENV["API_USERNAME"] %>
  api_password:           <%= ENV["API_PASSWORD"] %>
  aws_access_key_id:      <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key:  <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_bucket:             <%= ENV['AWS_BUCKET'] %>
  paypal_username:        <%= ENV['PAYPAL_USERNAME'] %>
  paypal_password:        <%= ENV['PAYPAL_PASSWORD'] %>
  paypal_signature:       <%= ENV['PAYPAL_SIGNATURE'] %>

production:
  secret_key_base:        <%= ENV["SECRET_KEY_BASE"] %>
  paypal_host:            <%= ENV["PAYPAL_HOST"] %>
  domain_url:             <%= ENV["DOMAIN_URL"] %>
  api_username:           <%= ENV["API_USERNAME"] %>
  api_password:           <%= ENV["API_PASSWORD"] %>
  aws_access_key_id:      <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key:  <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_bucket:             <%= ENV['AWS_BUCKET'] %>
  paypal_username:        <%= ENV['PAYPAL_USERNAME'] %>
  paypal_password:        <%= ENV['PAYPAL_PASSWORD'] %>
  paypal_signature:       <%= ENV['PAYPAL_SIGNATURE'] %>
